Homework_3
parfenovaaa/AnnaParfenova pull request #3
Opened 2021-11-07 00:26 UTC by parfenovaaa

2021-11-10 19:00 UTC, akulebyakin requested changes
Changes required. Please review comments.

2021-11-10 23:38 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/TestData.java
> +    public final String userName = "ROMAN IOVLEV";
moved userName to properties file

2021-11-10 23:38 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/components/LoginMenu.java
> +    }
GetProp() moves to new class GetProperties

2021-11-10 23:39 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/components/ElementsPage.java
> +    }
Method separated to clickOn() and getLog() methods

2021-11-10 23:39 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/components/ElementsPage.java
> +    }
ok

2021-11-10 23:39 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/components/ElementsPage.java
> +    }
Method changed to selectDropdownByVisibleText(String colour) method

2021-11-10 23:39 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/components/ElementsPage.java
> +    }
changed the logic of using ElementPage class

2021-11-10 23:39 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/components/ElementsPage.java
> +    WebElement waterCheckBox;
ok

2021-11-10 23:41 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/components/ElementsPage.java
> +    WebDriver webDriver;
guess it`s not necessary to use it in this class and in LoginMenu class, right?

2021-11-10 23:41 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/ex1/Exercise1.java
> +        TestData testData = new TestData();
ok

2021-11-10 23:41 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw3/TestData.java
> +    public final String title = "Home Page";
ok

2021-11-10 23:42 UTC, parfenovaaa commented on src/test/resources/com/epam/tc/hw3/Homework3TestSuite.xml
> +  </test>
ok, got it. Just wasn`t sure how to name test here)

2021-11-11 20:20 UTC, akulebyakin approved these changes
Approved!

2021-11-11 20:21 UTC, merged