Homework5
parfenovaaa/AnnaParfenova pull request #5
Opened 2021-11-17 14:19 UTC by parfenovaaa

2021-11-21 13:45 UTC, akulebyakin requested changes
Please review comments

2021-11-22 10:49 UTC, parfenovaaa commented on src/test/java/com/epam/tc/hw5/cucumber/steps/UserTableSteps.java
> +    }*/
ok

2021-11-22 10:50 UTC, parfenovaaa commented on src/test/resources/com/epam/tc/hw5/cucumber/Exercise1.feature
> +
Done. I just thought it`s similar to previous exercise.

2021-11-23 07:55 UTC, akulebyakin approved these changes
Approved

2021-11-23 12:49 UTC, merged